resolver: nightly-2019-04-05
packages: []

extra-deps:
  - archive: https://digitalassetsdk.bintray.com/ghc-lib/ghc-lib-parser-0.20190405.tar.gz
  - archive: https://digitalassetsdk.bintray.com/ghc-lib/ghc-lib-0.20190405.tar.gz
